data:
  N_rays: 512
  batch_size: 1
  cam_file: cameras_sphere.npz
  data_dir: /datawaha/cggroup/parawr/Projects/adobe/neumesh/data/editable_nerf/nerf_synthetic/chair
  downscale: 1
  pin_memory: true
  split: train
  type: DTU
  val_downscale: 1
  val_rayschunk: 16384
  obj_bounding_radius: 2
device_ids:
- 0
expname: blender_sheep
neumesh:
  N_samples: 100000
  batch_size: 512
  distance_method: frnn
  dump_samples: false
  input_xyz: false
  learn_indicator_vector: true
  loss_weights:
    eikonal: 0.001
  prior_mesh: /datawaha/cggroup/parawr/Projects/adobe/neumesh/data/editable_nerf/nerf_synthetic/chair/chair_triangulated_fixedrot.obj
  # prior_mesh: /home/parawr/Projects/adobe/neumesh/meshes/teacher/dtu_scan63/dtu_scan63.ply
  training_type: null
  union_training: true
  val_sampleschunk: 5000
model:
  N_nograd_samples: 2048
  N_upsample_iters: 4
  compute_bounded_near_far: true
  framework: NeuS
  mbgs:
    D_color: 4
    D_density: 3
    color_dim: 32
    geometry_dim: 32
    multires_d: 8
    multires_fg: 2
    multires_ft: 2
    multires_view: 4
  obj_bounding_radius: 3 # sheep is probably larger
  radiance:
    D: 4
    W: 256
    embed_multires: -1
    embed_multires_view: 4
    skips: []
  surface:
    D: 8
    W: 256
    embed_multires: 6
    radius_init: 2
    skips:
    - 4
  upsample_algo: official_solution
  variance_init: 0.05
  white_bkgd: false
training:
  overfit: True
  ckpt_file: null
  ckpt_ignore_keys: []
  ckpt_only_use_keys: null
  i_backup: 50000
  i_save: 900
  i_val: 10000
  i_val_mesh: 50000
  i_render: 1000
  log_root_dir: logs
  lr: 0.0005
  monitoring: tensorboard
  num_iters: 200000
  scheduler:
    type: warmupcosine
    warmup_steps: 5000
  speed_factor: 10.0
  val_mesh:
    N_grid: 256
    chunk: 2048
    obj_id: test
    scale_factor: 1.0
    sdf_th: 0.0
    x_range:
    - -1.2
    - 1.2
    y_range:
    - -1.2
    - 1.2
    z_range:
    - -1.2
    - 1.2
  w_eikonal: 0.1
  w_mask: 1.0
  with_mask: true
